//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        [StringLength(1000, MinimumLength = 2)]
        [Required]
        public string name { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = false)]
        public double price { get; set; }
        [Range(1, Int32.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        [Required]
        public int quantity { get; set; }
        [StringLength(1000, MinimumLength = 2)]
        [Required]
        public string image { get; set; }
        [StringLength(5000, MinimumLength = 2)]
        [Required]
        public string description { get; set; }
        [Range(0, Int32.MaxValue, ErrorMessage = "Please enter a value bigger than {0}")]
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
